# Generated by Django 5.1.7 on 2026-02-02 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tax_id', models.CharField(max_length=20, verbose_name='NIF/CIF')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('country', models.CharField(default='ES', max_length=2, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='Logo')),
                ('default_currency', models.CharField(default='EUR', max_length=3, verbose_name='Moneda por defecto')),
                ('legal_text', models.TextField(blank=True, verbose_name='Texto legal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Perfil de empresa',
                'verbose_name_plural': 'Perfiles de empresa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=21, max_digits=5, verbose_name='Tipo de IVA (%)')),
                ('default_withholding_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Retención IRPF (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='invoicing.businessprofile', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Artículo del catálogo',
                'verbose_name_plural': 'Artículos del catálogo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='NIF/CIF')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='invoicing.businessprofile', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Número')),
                ('series', models.CharField(blank=True, max_length=10, verbose_name='Serie')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('cancelled', 'Anulada')], default='draft', max_length=10, verbose_name='Estado')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Moneda')),
                ('issue_date', models.DateField(verbose_name='Fecha de emisión')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('legal_text', models.TextField(blank=True, verbose_name='Texto legal')),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoicing.businessprofile', verbose_name='Empresa')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issue_date', '-number'],
                'unique_together': {('business_profile', 'number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=21, max_digits=5, verbose_name='IVA (%)')),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Retención IRPF (%)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posición')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Línea de factura',
                'verbose_name_plural': 'Líneas de factura',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_prefix', models.CharField(default='F', max_length=10, verbose_name='Prefijo de serie')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Siguiente número')),
                ('format_pattern', models.CharField(default='{prefix}-{year}-{number:05d}', max_length=100, verbose_name='Patrón de formato')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbering_configs', to='invoicing.businessprofile', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Numeración de facturas',
                'verbose_name_plural': 'Numeraciones de facturas',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('primary_color', models.CharField(default='#1e3a5f', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#f0f4f8', max_length=7, verbose_name='Color secundario')),
                ('font_family', models.CharField(choices=[('sans-serif', 'Sans-serif'), ('serif', 'Serif'), ('monospace', 'Monospace')], default='sans-serif', max_length=20, verbose_name='Tipografía')),
                ('layout_variant', models.CharField(choices=[('classic', 'Clásico'), ('modern', 'Moderno'), ('minimal', 'Minimalista')], default='classic', max_length=10, verbose_name='Variante de diseño')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por defecto')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='invoicing.businessprofile', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tema de factura',
                'verbose_name_plural': 'Temas de factura',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('method', models.CharField(choices=[('transfer', 'Transferencia'), ('cash', 'Efectivo'), ('card', 'Tarjeta'), ('other', 'Otro')], default='transfer', max_length=10, verbose_name='Método de pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Editor'), ('viewer', 'Lector')], default='viewer', max_length=10, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='invoicing.businessprofile', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'unique_together': {('user', 'business_profile')},
            },
        ),
    ]
