# Generated by Django 5.1.7 on 2026-01-29 09:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[str] = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Año')),
                ('estimation_type', models.CharField(choices=[('simplified', 'Estimación directa simplificada'), ('normal', 'Estimación directa normal')], default='simplified', max_length=20, verbose_name='Tipo de estimación')),
                ('closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Año fiscal',
                'verbose_name_plural': 'Años fiscales',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, '1T (ene-mar)'), (2, '2T (abr-jun)'), (3, '3T (jul-sep)'), (4, '4T (oct-dic)')], verbose_name='Trimestre')),
                ('closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='freelance.fiscalyear', verbose_name='Año fiscal')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
                'ordering': ['fiscal_year__year', 'number'],
                'unique_together': {('fiscal_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('concept', models.CharField(max_length=255, verbose_name='Concepto')),
                ('client', models.CharField(blank=True, max_length=255, verbose_name='Cliente')),
                ('reference', models.CharField(blank=True, help_text='Nº factura', max_length=100, verbose_name='Referencia')),
                ('taxable_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base imponible')),
                ('vat_type', models.PositiveSmallIntegerField(choices=[(21, '21%'), (10, '10%'), (4, '4%'), (0, 'Exento')], default=21, verbose_name='Tipo de IVA')),
                ('output_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10, verbose_name='IVA repercutido')),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='% IRPF retenido (15% normal, 7% inicio actividad)', max_digits=4, verbose_name='% Retención')),
                ('withholding', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10, verbose_name='Retención')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='freelance.quarter', verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('concept', models.CharField(max_length=255, verbose_name='Concepto')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Proveedor')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('category', models.CharField(choices=[('social_security', 'Cuota de autónomos'), ('software', 'Software y suscripciones'), ('supplies', 'Material de oficina'), ('telecom', 'Telefonía e internet'), ('training', 'Formación'), ('services', 'Servicios profesionales'), ('other', 'Otros gastos deducibles')], default='other', max_length=20, verbose_name='Categoría')),
                ('taxable_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base imponible')),
                ('vat_type', models.PositiveSmallIntegerField(choices=[(21, '21%'), (10, '10%'), (4, '4%'), (0, 'Exento')], default=21, verbose_name='Tipo de IVA')),
                ('input_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10, verbose_name='IVA soportado')),
                ('irpf_deductible', models.BooleanField(default=True, verbose_name='Deducible IRPF')),
                ('vat_deductible', models.BooleanField(default=True, verbose_name='Deducible IVA')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='freelance.quarter', verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_303_calculated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Modelo 303 calculado')),
                ('modelo_303_submitted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Modelo 303 presentado')),
                ('modelo_130_calculated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Modelo 130 calculado')),
                ('modelo_130_submitted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Modelo 130 presentado')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Fecha de presentación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='freelance.quarter', verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Resultado trimestral',
                'verbose_name_plural': 'Resultados trimestrales',
            },
        ),
    ]
